### ISSUE TITLE
Bruh lemme explain

### ISSUE THREAD

**Issue by Imshubh69** [rk134/local_manifests#1]
Man where did you generated these dope readme which is present in your profile cause i haven't found any which can generate readme like it

**Comment by rk134** [comment]
I shamelessly kanged it from @PrajjuS, and added my own modifications

**Comment by PrajjuS** [comment]
Lol

**Comment by Imshubh69** [comment]
> Lol

You tell @PrajjuS from where did you generated that holy shit

**Comment by PrajjuS** [comment]
> > Lol
> 
> You tell @PrajjuS from where did you generated that holy shit

Made myself lol
